remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Selbstbestimmt statt fremdbespaßt
description: Ideen für die Herbstferien 2022
show_downloads: false
google_analytics: 
